<a href="https://colab.research.google.com/github/teenathirumala/ML/blob/main/datapreprocessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **DATA PREPROCESSING tools**:

**IMPORTING LIBRARIES**

In [2]:
# numpy will allow us to work with arrays
# matplotlib -to plot charts graphs
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

**IMPORTING DATASET**

features are the columns with which you arte going to determine the dependent variables
And the dependent variable is last column

In [3]:
dataset=pd.read_csv('Data.csv')
x=dataset.iloc[:, :-1].values
y=dataset.iloc[:, -1].values

In [ ]:
print(x)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


In [ ]:
print(y)

['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


**TAKE CARE OF MISSING VALUES**

In [ ]:
from sklearn.impute import SimpleImputer
imputer=SimpleImputer(missing_values=np.nan,strategy='mean')
imputer.fit(x[:, 1:3])
x[:, 1:3]=imputer.transform(x[:, 1:3])

In [ ]:
print(x)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


**ENCODING CATEGORICAL DATA**

**Encoding** **the independent variable**

In [4]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct=ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[0])],remainder='passthrough')
x=np.array(ct.fit_transform(x))

In [5]:
print(x)

[[1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 40.0 nan]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 nan 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


**Encoding the dependent variable**

In [7]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
y=le.fit_transform(y)

In [8]:
print(y)

[0 1 0 0 1 1 0 1 0 1]


**splitting the dataset into training set and tesing set**

In [9]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=1)

In [10]:
print(x_train)

[[0.0 0.0 1.0 nan 52000.0]
 [0.0 1.0 0.0 40.0 nan]
 [1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 35.0 58000.0]]


In [11]:
print(x_test)

[[0.0 1.0 0.0 30.0 54000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


In [12]:
print(y_train)

[0 1 0 0 1 1 0 1]


In [13]:
print(y_test)

[0 1]


**Feature scaling**



In [16]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train[:,3:]=sc.fit_transform(x_train[:,3:])
x_test[:,3:]=sc.transform(x_test[:,3:])

In [17]:
print(x_train)

[[0.0 0.0 1.0 nan -1.0182239953527132]
 [0.0 1.0 0.0 -0.038910211282047996 nan]
 [1.0 0.0 0.0 0.5058327466666259 0.583476671494251]
 [0.0 0.0 1.0 -0.3112816902563849 -0.2974586952715793]
 [0.0 0.0 1.0 -1.809324824615238 -1.3385641287221062]
 [1.0 0.0 0.0 1.0505757046152997 1.1440719048906884]
 [0.0 1.0 0.0 1.3229471835896367 1.4644120382600814]
 [1.0 0.0 0.0 -0.7198389087178904 -0.537713795298624]]


In [18]:
print(x_test)

[[0.0 1.0 0.0 -1.4007676061537326 -0.8580539286680168]
 [1.0 0.0 0.0 -0.4474674297435534 0.18305150478250995]]
